export {
  CoreVisualStyleSchema,
  DecorationIntensitySchema,
  DecorationPatternSchema,
  MotionIntensitySchema,
  StyleAssetGuidanceSchema,
  StyleAudienceStageSchema,
  StyleColorSchemeSchema,
  StyleColorTokensSchema,
  StyleContentAffordanceSchema,
  StyleDecorationSchema,
  StyleDomainSchema,
  StyleFormalitySchema,
  StyleLearningActivitySchema,
  StyleMotionSchema,
  StyleNarrativeModeSchema,
  StyleRiskContextSchema,
  StyleSpacingSchema,
  StyleSurfaceSchema,
  StyleTemplateFamilySchema,
  StyleTemplateProfileSchema,
  StyleTemplateSchema,
  StyleTypographySchema,
  type CoreVisualStyle,
  type StyleAssetGuidance,
  type StyleAudienceStage,
  type StyleColorScheme,
  type StyleColorTokens,
  type StyleContentAffordance,
  type StyleDecoration,
  type StyleDomain,
  type StyleFormality,
  type StyleLearningActivity,
  type StyleMotion,
  type StyleNarrativeMode,
  type StyleRiskContext,
  type StyleSpacing,
  type StyleSurface,
  type StyleTemplateFamily,
  type StyleTemplateProfile,
  type StyleTemplate,
  type StyleTypography,
} from "./schema";
export {
  inferStyleIntent,
  rankStyleTemplates,
  type RankedStyleTemplate,
  type StyleCandidateRole,
  type StyleIntentProfile,
  type StyleMatchFactor,
} from "./matching";
export { styleTemplates } from "./templates";
export {
  getStyleTemplate,
  listStyleTemplates,
  searchStyleTemplates,
  type StyleTemplateMatch,
  type StyleTemplateSearchInput,
} from "./registry";
export {
  styleTemplateToCssText,
  styleTemplateToCssVariables,
  styleTemplateToTheme,
  type CourseCssVariableName,
  type CourseCssVariables,
} from "./style-to-css";
