import { StyleTemplateSchema } from "./schema";

/**
 * 从 frontend-slides bold 配方中提升为生产参考的视觉方向。
 * 这里只保存可匹配的视觉语义与 token；Page Creator 仍自主编排 HTML。
 */
export const extendedStyleTemplates = StyleTemplateSchema.array()
  .length(4)
  .parse([
    {
      id: "neo-grid-bold",
      name: "霓黄编辑网格",
      visualStyle: "minimal",
      profile: {
        family: "editorial",
        formality: "medium",
        scheme: "light",
        domains: ["stem", "business", "creative", "general"],
        audienceStages: ["secondary", "higher-education", "professional", "general"],
        learningActivities: ["explain", "compare", "derive"],
        narrativeModes: ["argument", "case-study", "reference"],
        contentAffordances: ["chart", "table", "diagram", "code"],
        riskContexts: ["standard"],
        tones: ["自信", "现代", "编辑", "锐利"],
        safeDefault: false,
        inspirationTemplate: "neo-grid-bold",
        recipePath: "agent/skills/frontend-slides/bold-template-pack/templates/neo-grid-bold/design.md",
      },
      goal: "用纸张底色、墨黑区块和单一霓黄信号色建立高密度编辑网格，让数据、比较和流程像设计年鉴而不是仪表盘。",
      colorTokens: { background: "#ECECE8", surface: "#F5F4EF", surfaceAlt: "#0A0A0A", text: "#0A0A0A", mutedText: "#6F6F6A", primary: "#E6FF3D", accent: "#0A0A0A", border: "#B9B9B2", success: "#2E8B57", warning: "#A86800", danger: "#C43A31" },
      typography: { headingFont: '"Noto Sans SC", "Space Grotesk", sans-serif', bodyFont: '"Noto Sans SC", "JetBrains Mono", sans-serif', headingWeight: 700, bodyWeight: 400, baseFontSize: "1rem", bodyLineHeight: 1.5 },
      spacing: { unit: "0.25rem", sectionGap: "1.25rem", cardGap: "0.75rem", contentMaxWidth: "112rem" },
      surface: { cardRadius: "0px", controlRadius: "0px", cardBorderWidth: "2px", cardShadow: "none" },
      decoration: { pattern: "broadside-grid", backgroundImage: "linear-gradient(rgba(10,10,10,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(10,10,10,.05) 1px,transparent 1px)", intensity: "bold", shapeLanguage: "十二列编辑网格、墨黑反白面、霓黄信号块、角标印记和等宽元数据" },
      motion: { durationFast: "120ms", durationNormal: "360ms", easing: "cubic-bezier(0.16, 1, 0.3, 1)", intensity: "subtle", reducedMotionDuration: "0ms" },
      layoutDensity: "compact",
      assetGuidance: { visualStyle: "高对比编辑摄影、硬边数据图形与印刷式裁切", composition: "主对象服从十二列网格，可跨列但不遮挡文字安全区", background: "暖灰纸面、墨黑区块和单一霓黄信号", avoid: ["圆角卡片墙", "多彩渐变", "弱层级小字堆叠"] },
      bestFor: ["数据比较", "流程与系统", "设计和商业分析", "观点型科学课程"],
      avoidFor: ["低龄柔和启蒙", "需要安静长文阅读的课程"],
      keywords: ["编辑网格", "新粗野", "霓黄", "数据", "比较", "流程", "设计"],
    },
    {
      id: "soft-editorial",
      name: "柔和文学编辑",
      visualStyle: "nature",
      profile: {
        family: "editorial",
        formality: "high",
        scheme: "light",
        domains: ["humanities", "creative", "life", "general"],
        audienceStages: ["higher-education", "professional", "general"],
        learningActivities: ["explain", "compare", "remember"],
        narrativeModes: ["story", "case-study", "reference"],
        contentAffordances: ["long-text", "photography", "timeline"],
        riskContexts: ["standard", "care"],
        tones: ["文学", "温暖", "从容", "杂志"],
        safeDefault: false,
        inspirationTemplate: "soft-editorial",
        recipePath: "agent/skills/frontend-slides/bold-template-pack/templates/soft-editorial/design.md",
      },
      goal: "用暖纸底、中文衬线标题、克制的粉彩面与杂志式留白承载叙事和长文，让课程具有小型文学季刊的温度。",
      colorTokens: { background: "#F2EEDF", surface: "#FBF8ED", surfaceAlt: "#E8C9B6", text: "#2A241B", mutedText: "#5C5345", primary: "#B7C7A8", accent: "#E1A4C2", border: "#D4CCB8", success: "#658A66", warning: "#A37728", danger: "#A85151" },
      typography: { headingFont: '"Noto Serif SC", "Cormorant Garamond", serif', bodyFont: '"Noto Sans SC", "Work Sans", sans-serif', headingWeight: 500, bodyWeight: 400, baseFontSize: "1rem", bodyLineHeight: 1.7 },
      spacing: { unit: "0.25rem", sectionGap: "1.75rem", cardGap: "1rem", contentMaxWidth: "104rem" },
      surface: { cardRadius: "1.5rem", controlRadius: "999px", cardBorderWidth: "1px", cardShadow: "0 18px 45px rgba(74,61,40,.10)" },
      decoration: { pattern: "editorial-glow", backgroundImage: "radial-gradient(circle at 85% 12%,rgba(225,164,194,.22),transparent 28%),radial-gradient(circle at 8% 88%,rgba(183,199,168,.24),transparent 26%)", intensity: "subtle", shapeLanguage: "暖纸张、衬线大小字对奏、粉彩满版切片、细注释和少量柔和圆角" },
      motion: { durationFast: "160ms", durationNormal: "520ms", easing: "cubic-bezier(0.22, 1, 0.36, 1)", intensity: "subtle", reducedMotionDuration: "0ms" },
      layoutDensity: "spacious",
      assetGuidance: { visualStyle: "温暖编辑摄影、自然光、纸张与轻微套色印刷感", composition: "单一主视觉与大标题形成杂志跨页关系，保留大块安静留白", background: "暖米纸色和低饱和粉彩切片", avoid: ["冷色企业仪表盘", "霓虹发光", "同权卡片矩阵"] },
      bestFor: ["文学与文化", "人物故事", "生活与关怀", "图文叙事"],
      avoidFor: ["高压闯关", "高密度代码和表格"],
      keywords: ["文学", "杂志", "暖纸", "柔和", "叙事", "文化", "人物"],
    },
    {
      id: "cartesian",
      name: "笛卡尔博物志",
      visualStyle: "minimal",
      profile: {
        family: "authority",
        formality: "high",
        scheme: "light",
        domains: ["stem", "humanities", "business", "general"],
        audienceStages: ["higher-education", "professional", "general"],
        learningActivities: ["explain", "derive", "compare"],
        narrativeModes: ["argument", "reference", "case-study"],
        contentAffordances: ["formula", "diagram", "table", "long-text"],
        riskContexts: ["standard", "regulated"],
        tones: ["克制", "严谨", "古典", "安静"],
        safeDefault: true,
        inspirationTemplate: "cartesian",
        recipePath: "agent/skills/frontend-slides/bold-template-pack/templates/cartesian/design.md",
      },
      goal: "以暖石色、单像素制图线和古典衬线标题建立博物馆目录式权威感，依靠比例和留白表达严谨而非堆叠面板。",
      colorTokens: { background: "#EDE8E0", surface: "#F5F1EA", surfaceAlt: "#E2DBD1", text: "#1A1A1A", mutedText: "#5A5A5A", primary: "#8A8178", accent: "#3D5864", border: "#B8B0A4", success: "#4D7860", warning: "#956A2C", danger: "#984B45" },
      typography: { headingFont: '"Noto Serif SC", "Playfair Display", serif', bodyFont: '"Noto Sans SC", sans-serif', headingWeight: 400, bodyWeight: 400, baseFontSize: "1rem", bodyLineHeight: 1.6 },
      spacing: { unit: "0.25rem", sectionGap: "2rem", cardGap: "1rem", contentMaxWidth: "108rem" },
      surface: { cardRadius: "0px", controlRadius: "0px", cardBorderWidth: "1px", cardShadow: "none" },
      decoration: { pattern: "none", backgroundImage: "radial-gradient(circle at 84% 20%,transparent 0 13%,rgba(138,129,120,.18) 13.2% 13.4%,transparent 13.6%)", intensity: "subtle", shapeLanguage: "一像素灰褐分隔线、圆规弧线、坐标刻度、窄栏注释和大面积暖石留白" },
      motion: { durationFast: "140ms", durationNormal: "420ms", easing: "cubic-bezier(0.22, 1, 0.36, 1)", intensity: "subtle", reducedMotionDuration: "0ms" },
      layoutDensity: "comfortable",
      assetGuidance: { visualStyle: "博物馆目录摄影、建筑制图和低饱和研究图示", composition: "图像或图形严格对齐基线与细分隔线，四周保留充足留白", background: "暖砂岩纸面与低对比制图圆弧", avoid: ["高饱和强调色", "厚阴影", "圆角 SaaS 卡片"] },
      bestFor: ["研究与白皮书", "数学和科学推导", "历史档案", "合规与专业学习"],
      avoidFor: ["低龄游戏化", "需要强烈舞台冲击的主题"],
      keywords: ["笛卡尔", "制图", "博物馆", "研究", "公式", "严谨", "档案"],
    },
    {
      id: "studio-electric",
      name: "电黄设计工作室",
      visualStyle: "broadside",
      profile: {
        family: "immersive",
        formality: "medium",
        scheme: "dark",
        domains: ["creative", "business", "stem", "general"],
        audienceStages: ["secondary", "higher-education", "professional", "general"],
        learningActivities: ["explain", "compare", "remember"],
        narrativeModes: ["argument", "case-study", "tutorial"],
        contentAffordances: ["photography", "diagram", "chart"],
        riskContexts: ["standard"],
        tones: ["电感", "大胆", "图形", "高对比"],
        safeDefault: false,
        inspirationTemplate: "studio",
        recipePath: "agent/skills/frontend-slides/bold-template-pack/templates/studio/design.md",
      },
      goal: "用近黑与电黄二元色、作为图形质量的超大标题和严格平面构成，打造有品牌声明感的高能课程舞台。",
      colorTokens: { background: "#1C1C1C", surface: "#242422", surfaceAlt: "#F5D200", text: "#F5D200", mutedText: "#C7B95B", primary: "#F5D200", accent: "#F7F4E8", border: "#3D3D38", success: "#7FD18B", warning: "#F5D200", danger: "#FF705F" },
      typography: { headingFont: '"Noto Sans SC", "Barlow", sans-serif', bodyFont: '"Noto Sans SC", sans-serif', headingWeight: 900, bodyWeight: 400, baseFontSize: "1rem", bodyLineHeight: 1.45 },
      spacing: { unit: "0.25rem", sectionGap: "1.25rem", cardGap: "0.75rem", contentMaxWidth: "112rem" },
      surface: { cardRadius: "0px", controlRadius: "0px", cardBorderWidth: "1px", cardShadow: "none" },
      decoration: { pattern: "none", backgroundImage: "linear-gradient(125deg,transparent 0 72%,rgba(245,210,0,.08) 72% 100%)", intensity: "bold", shapeLanguage: "超大重字、近黑与电黄整面反转、等宽页脚、硬边裁切和无装饰平面" },
      motion: { durationFast: "110ms", durationNormal: "380ms", easing: "cubic-bezier(0.16, 1, 0.3, 1)", intensity: "dynamic", reducedMotionDuration: "0ms" },
      layoutDensity: "spacious",
      assetGuidance: { visualStyle: "黑黄高反差摄影、硬光对象特写和品牌海报式裁切", composition: "让单一对象或标题成为视觉质量，避免多个小图争夺注意力", background: "近黑或整面电黄，禁止第三种主色", avoid: ["柔和粉彩", "玻璃拟态", "细碎装饰图标"] },
      bestFor: ["创意与品牌", "观点型商业课程", "技术主题开场", "高冲击总结"],
      avoidFor: ["医疗合规", "安静长文阅读", "低龄柔和启蒙"],
      keywords: ["工作室", "电黄", "黑黄", "品牌", "高对比", "海报", "大胆"],
    },
  ]);
