import { StyleTemplateSchema } from "./schema";

const definitions = [
  {
    id: "sci-fi",
    name: "科幻探索",
    visualStyle: "sci-fi",
    goal: "用深色空间、冷色发光边缘和精密网格建立未来探索感。",
    colorTokens: {
      background: "#07111F",
      surface: "#0D1D2E",
      surfaceAlt: "#132A3F",
      text: "#EAFBFF",
      mutedText: "#94B8C7",
      primary: "#5EEBFF",
      accent: "#9B7BFF",
      border: "#1E5A78",
      success: "#3DDC97",
      warning: "#FFC857",
      danger: "#FF6B7A",
    },
    typography: {
      headingFont: '"Space Grotesk", "Noto Sans SC", sans-serif',
      bodyFont: '"Inter", "Noto Sans SC", sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      baseFontSize: "1rem",
      bodyLineHeight: 1.65,
    },
    spacing: {
      unit: "0.25rem",
      sectionGap: "2rem",
      cardGap: "1rem",
      contentMaxWidth: "72rem",
    },
    surface: {
      cardRadius: "0.75rem",
      controlRadius: "0.5rem",
      cardBorderWidth: "1px",
      cardShadow: "0 18px 45px rgba(0, 190, 255, 0.16)",
    },
    decoration: {
      pattern: "stars",
      backgroundImage:
        "radial-gradient(circle at 20% 20%, rgba(94,235,255,.18), transparent 32%)",
      intensity: "moderate",
      shapeLanguage: "细网格、轨道弧线、发光描边和精密仪表元素",
    },
    motion: {
      durationFast: "140ms",
      durationNormal: "280ms",
      easing: "cubic-bezier(0.22, 1, 0.36, 1)",
      intensity: "subtle",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "compact",
    assetGuidance: {
      visualStyle: "电影级科幻概念图、冷色光源、清晰主体轮廓",
      composition: "主体居中或使用探索路径引导视线，保留文本安全区",
      background: "深色空间、抽象数据网格或克制星点",
      avoid: ["暖色卡通贴纸", "复古纸张纹理", "高噪点复杂背景"],
    },
    bestFor: ["太空与未来科技", "工程探索", "数据和系统主题"],
    avoidFor: ["低龄生活习惯课程", "传统文化古典叙事", "自然观察手账"],
    keywords: ["科幻", "太空", "未来", "科技", "宇宙", "探索", "数据"],
  },
  {
    id: "editorial-night",
    name: "深夜编辑杂志",
    visualStyle: "editorial-night",
    goal:
      "用深靛蓝色场、暖金衬线标题、薄分隔线和非对称编辑网格建立有辨识度的夜间杂志阅读体验，避免通用白卡和 SaaS 面板感。",
    colorTokens: {
      background: "#0B1020",
      surface: "#151C30",
      surfaceAlt: "#202A42",
      text: "#F5F1E8",
      mutedText: "#AAB4CA",
      primary: "#F2C66D",
      accent: "#74E1CF",
      border: "#35415E",
      success: "#77D5A5",
      warning: "#E8B75F",
      danger: "#F17C88",
    },
    typography: {
      headingFont:
        '"Noto Serif SC", "Source Han Serif SC", Georgia, serif',
      bodyFont: '"IBM Plex Sans", "Noto Sans SC", Arial, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      baseFontSize: "1rem",
      bodyLineHeight: 1.6,
    },
    spacing: {
      unit: "0.25rem",
      sectionGap: "1.75rem",
      cardGap: "0.875rem",
      contentMaxWidth: "74rem",
    },
    surface: {
      cardRadius: "0.25rem",
      controlRadius: "0.25rem",
      cardBorderWidth: "1px",
      cardShadow: "0 18px 48px rgba(0, 0, 0, 0.3)",
    },
    decoration: {
      pattern: "editorial-glow",
      backgroundImage:
        "radial-gradient(circle at 82% 18%, rgba(116,225,207,.18), transparent 28%), radial-gradient(circle at 12% 88%, rgba(242,198,109,.12), transparent 24%)",
      intensity: "moderate",
      shapeLanguage:
        "细金色规则线、超大章节数字、窄栏旁注、深色满版和少量柔焦光晕；优先排版构图，避免重复圆角卡片",
    },
    motion: {
      durationFast: "140ms",
      durationNormal: "260ms",
      easing: "cubic-bezier(0.22, 1, 0.36, 1)",
      intensity: "subtle",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "compact",
    assetGuidance: {
      visualStyle:
        "深夜编辑摄影或低照度科学插画，深靛蓝底色、暖金与极光薄荷色点缀，克制颗粒质感",
      composition:
        "使用杂志跨页式非对称构图，让单一主视觉占据一侧并为标题、旁注和互动留下明确安全区",
      background:
        "深色满版夜空、抽象柔焦光晕或低细节天文环境，不使用白色卡片墙",
      avoid: [
        "通用白色卡片网格",
        "SaaS 仪表盘式蓝色按钮堆叠",
        "霓虹赛博朋克过度发光",
        "与教学目标无关的星星装饰",
      ],
    },
    bestFor: ["天文与夜空", "文化与艺术", "高端成人学习", "叙事型科学课程"],
    avoidFor: ["低龄儿童贴纸课程", "明亮运动游戏", "需要浅色打印的表格密集参考"],
    keywords: [
      "深夜",
      "夜间",
      "夜空",
      "编辑",
      "杂志",
      "editorial",
      "天文",
      "极光",
      "暗色",
      "高级",
    ],
  },
  {
    id: "broadside",
    name: "火焰大字报",
    visualStyle: "broadside",
    goal:
      "借鉴 frontend-slides Broadside 的抗议海报编辑系统：用墨黑与火焰橙双场景、超大中文重字、目录式小字、发丝分隔线和代码原生图形，让课程页像一张有冲击力的文化海报而不是卡片面板。",
    colorTokens: {
      background: "#111111",
      surface: "#1A1A18",
      surfaceAlt: "#282826",
      text: "#F0ECE5",
      mutedText: "#888880",
      primary: "#E85D26",
      accent: "#F0ECE5",
      border: "#30302D",
      success: "#68C99A",
      warning: "#E8A526",
      danger: "#E7655F",
    },
    typography: {
      headingFont:
        '"Noto Serif SC", "Source Han Serif SC", "Songti SC", serif',
      bodyFont:
        '"LXGW WenKai", "Noto Serif SC", "Source Han Serif SC", serif',
      headingWeight: 900,
      bodyWeight: 400,
      baseFontSize: "1rem",
      bodyLineHeight: 1.75,
    },
    spacing: {
      unit: "0.25rem",
      sectionGap: "1.5rem",
      cardGap: "1rem",
      contentMaxWidth: "90rem",
    },
    surface: {
      cardRadius: "0px",
      controlRadius: "0px",
      cardBorderWidth: "1px",
      cardShadow: "none",
    },
    decoration: {
      pattern: "broadside-grid",
      backgroundImage:
        "linear-gradient(rgba(240,236,229,.045) 1px, transparent 1px), linear-gradient(90deg, rgba(240,236,229,.045) 1px, transparent 1px)",
      intensity: "bold",
      shapeLanguage:
        "超大中文重字充当图形、火焰橙满版宣言面、细发丝分隔线、斜杠项目符号、目录编号、非对称两栏、图表与轨道式代码原生图示；无圆角卡片和阴影。",
    },
    motion: {
      durationFast: "180ms",
      durationNormal: "650ms",
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      intensity: "dynamic",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "spacious",
    assetGuidance: {
      visualStyle:
        "高对比编辑摄影或科学对象特写，墨黑背景、火焰橙单一强调色、温暖纸张颗粒、硬边裁切和海报印刷质感",
      composition:
        "主视觉占一侧 45%–60%，另一侧由超大标题与目录式信息构成；允许对象越出常规网格，但必须保留文字安全区",
      background:
        "墨黑或火焰橙满版，使用低对比网格、颗粒和单一大形体，不使用白色卡片墙",
      avoid: [
        "圆角卡片网格与仪表盘布局",
        "多种霓虹强调色和紫色渐变",
        "小标题、小插图漂浮在大片空白中",
        "阴影、玻璃拟态和柔软胶囊控件",
      ],
    },
    bestFor: [
      "需要强烈观点的科学与文化课程",
      "中文编辑叙事",
      "成人学习与设计主题",
      "海报式演讲课程",
    ],
    avoidFor: ["低龄柔和启蒙", "传统企业合规", "需要打印的密集表格"],
    keywords: [
      "broadside",
      "frontend-slides",
      "大字报",
      "海报",
      "编辑",
      "戏剧",
      "强烈",
      "火焰橙",
      "墨黑",
      "丰富",
      "绚丽",
      "视觉冲击",
    ],
  },
  {
    id: "kids-playful",
    name: "儿童趣味",
    visualStyle: "kids-playful",
    goal: "用明亮色彩、圆润形状和友好反馈营造轻松的儿童学习体验。",
    colorTokens: {
      background: "#FFF8E8",
      surface: "#FFFFFF",
      surfaceAlt: "#FFF0C7",
      text: "#25324A",
      mutedText: "#667085",
      primary: "#5B7CFA",
      accent: "#FF8A5B",
      border: "#D9E2FF",
      success: "#25B987",
      warning: "#F4B740",
      danger: "#E85D75",
    },
    typography: {
      headingFont: '"Nunito", "Noto Sans SC", sans-serif',
      bodyFont: '"Noto Sans SC", "Arial", sans-serif',
      headingWeight: 800,
      bodyWeight: 500,
      baseFontSize: "1.0625rem",
      bodyLineHeight: 1.7,
    },
    spacing: {
      unit: "0.375rem",
      sectionGap: "2.5rem",
      cardGap: "1.25rem",
      contentMaxWidth: "68rem",
    },
    surface: {
      cardRadius: "1.5rem",
      controlRadius: "999px",
      cardBorderWidth: "2px",
      cardShadow: "0 12px 0 rgba(91, 124, 250, 0.12)",
    },
    decoration: {
      pattern: "bubbles",
      backgroundImage:
        "radial-gradient(circle at 85% 15%, rgba(255,138,91,.2), transparent 28%)",
      intensity: "bold",
      shapeLanguage: "圆点、弧线、贴纸轮廓和轻量不规则几何形",
    },
    motion: {
      durationFast: "160ms",
      durationNormal: "320ms",
      easing: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      intensity: "dynamic",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "spacious",
    assetGuidance: {
      visualStyle: "高明度儿童插画、清晰表情、柔和描边和简单造型",
      composition: "单一主角或少量对象，动作明确，留出大块文字空间",
      background: "浅色、低细节、使用少量彩色气泡或贴纸元素",
      avoid: ["暗黑恐怖氛围", "写实暴力", "密集小字和复杂仪表盘"],
    },
    bestFor: ["儿童启蒙", "轻量互动练习", "游戏化入门课程"],
    avoidFor: ["严肃合规培训", "高密度专业参考", "沉浸式暗色科幻"],
    keywords: ["儿童", "童趣", "活泼", "可爱", "明亮", "启蒙", "孩子"],
  },
  {
    id: "minimal",
    name: "极简专业",
    visualStyle: "minimal",
    goal: "用克制配色、精确层级和充足留白呈现可靠、高效的专业内容。",
    colorTokens: {
      background: "#F7F8FA",
      surface: "#FFFFFF",
      surfaceAlt: "#EEF1F5",
      text: "#172033",
      mutedText: "#667085",
      primary: "#315EFB",
      accent: "#7A5AF8",
      border: "#D8DEE8",
      success: "#14866D",
      warning: "#B7791F",
      danger: "#C43248",
    },
    typography: {
      headingFont: '"Inter", "Noto Sans SC", sans-serif',
      bodyFont: '"Inter", "Noto Sans SC", sans-serif',
      headingWeight: 650,
      bodyWeight: 400,
      baseFontSize: "1rem",
      bodyLineHeight: 1.65,
    },
    spacing: {
      unit: "0.25rem",
      sectionGap: "2rem",
      cardGap: "1rem",
      contentMaxWidth: "76rem",
    },
    surface: {
      cardRadius: "0.625rem",
      controlRadius: "0.5rem",
      cardBorderWidth: "1px",
      cardShadow: "0 8px 24px rgba(16, 24, 40, 0.08)",
    },
    decoration: {
      pattern: "none",
      backgroundImage: "linear-gradient(180deg, rgba(49,94,251,.04), transparent 35%)",
      intensity: "subtle",
      shapeLanguage: "规则网格、细分隔线、克制圆角和清晰数据层级",
    },
    motion: {
      durationFast: "120ms",
      durationNormal: "220ms",
      easing: "cubic-bezier(0.2, 0, 0, 1)",
      intensity: "subtle",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "compact",
    assetGuidance: {
      visualStyle: "干净的编辑摄影、简洁信息图或高质量产品示意",
      composition: "明确网格、主体对齐、留白充分并保持信息优先",
      background: "中性浅色、单色或非常克制的环境背景",
      avoid: ["过度装饰", "卡通贴纸", "多重渐变和强烈发光效果"],
    },
    bestFor: ["企业培训", "专业知识", "信息密集型课程", "管理与技能提升"],
    avoidFor: ["强剧情儿童冒险", "需要黑板手写感的课堂", "高装饰游戏任务"],
    keywords: ["极简", "专业", "企业", "商务", "克制", "清晰", "职场"],
  },
  {
    id: "nature",
    name: "自然观察",
    visualStyle: "nature",
    goal: "用植物色系、标本式组织和柔和材质建立安静的自然观察氛围。",
    colorTokens: {
      background: "#F3F6ED",
      surface: "#FFFEF8",
      surfaceAlt: "#E6EEDB",
      text: "#26362A",
      mutedText: "#68766A",
      primary: "#4F7A55",
      accent: "#C77B4A",
      border: "#C9D8C3",
      success: "#3E8B61",
      warning: "#C28B2C",
      danger: "#B75C54",
    },
    typography: {
      headingFont: '"Lora", "Noto Serif SC", serif',
      bodyFont: '"Noto Sans SC", "Arial", sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      baseFontSize: "1rem",
      bodyLineHeight: 1.75,
    },
    spacing: {
      unit: "0.375rem",
      sectionGap: "2.75rem",
      cardGap: "1.25rem",
      contentMaxWidth: "70rem",
    },
    surface: {
      cardRadius: "0.75rem",
      controlRadius: "0.5rem",
      cardBorderWidth: "1px",
      cardShadow: "0 10px 28px rgba(52, 78, 55, 0.1)",
    },
    decoration: {
      pattern: "botanical",
      backgroundImage:
        "radial-gradient(circle at 10% 10%, rgba(79,122,85,.13), transparent 30%)",
      intensity: "subtle",
      shapeLanguage: "叶片轮廓、标本标签、柔和有机曲线和手账式分区",
    },
    motion: {
      durationFast: "180ms",
      durationNormal: "360ms",
      easing: "cubic-bezier(0.22, 0.61, 0.36, 1)",
      intensity: "subtle",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "comfortable",
    assetGuidance: {
      visualStyle: "自然光摄影、科学插画、标本图或观察记录风格",
      composition: "突出单一物种或生态关系，保留标签与注释空间",
      background: "自然材质、浅色纸张或柔和环境虚化",
      avoid: ["霓虹科幻光效", "过度拟人卡通", "人工感很强的商务图库"],
    },
    bestFor: ["生物与生态", "户外观察", "环境教育", "健康生活主题"],
    avoidFor: ["高科技仪表盘", "竞技游戏任务", "严肃财务培训"],
    keywords: ["自然", "植物", "动物", "生态", "观察", "环境", "生物"],
  },
  {
    id: "blackboard",
    name: "黑板课堂",
    visualStyle: "blackboard",
    goal: "用深色板面、粉笔高亮和手写注释还原专注的课堂推导体验。",
    colorTokens: {
      background: "#162E2A",
      surface: "#1F3D37",
      surfaceAlt: "#294A43",
      text: "#F4F0DF",
      mutedText: "#C9C3AF",
      primary: "#F3DF76",
      accent: "#E78B7B",
      border: "#4F6B63",
      success: "#8FD694",
      warning: "#F3C969",
      danger: "#F08A82",
    },
    typography: {
      headingFont: '"Kalam", "Noto Sans SC", sans-serif',
      bodyFont: '"Noto Sans SC", "Arial", sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      baseFontSize: "1.0625rem",
      bodyLineHeight: 1.75,
    },
    spacing: {
      unit: "0.375rem",
      sectionGap: "2.5rem",
      cardGap: "1.25rem",
      contentMaxWidth: "72rem",
    },
    surface: {
      cardRadius: "0.375rem",
      controlRadius: "0.25rem",
      cardBorderWidth: "1px",
      cardShadow: "0 10px 24px rgba(0, 0, 0, 0.22)",
    },
    decoration: {
      pattern: "chalk",
      backgroundImage:
        "linear-gradient(110deg, rgba(255,255,255,.025), transparent 45%, rgba(255,255,255,.02))",
      intensity: "moderate",
      shapeLanguage: "粉笔下划线、手绘箭头、板书分区和轻微擦拭纹理",
    },
    motion: {
      durationFast: "150ms",
      durationNormal: "260ms",
      easing: "ease-out",
      intensity: "subtle",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "comfortable",
    assetGuidance: {
      visualStyle: "粉笔示意图、手绘公式、课堂板书和简单教学图形",
      composition: "像教师板书一样从左到右组织，重点使用圈画和箭头",
      background: "深绿或炭黑板面，保留轻微粉笔纹理",
      avoid: ["精密 3D 渲染", "高饱和霓虹", "复杂写实场景背景"],
    },
    bestFor: ["数学推导", "课堂讲解", "公式与步骤", "传统学科复习"],
    avoidFor: ["品牌企业展示", "儿童贴纸游戏", "写实自然摄影课程"],
    keywords: ["黑板", "课堂", "板书", "粉笔", "数学", "公式", "老师"],
  },
  {
    id: "game-quest",
    name: "游戏任务",
    visualStyle: "game-quest",
    goal: "用任务面板、进度反馈和成就语言构建清晰但不过度娱乐化的挑战体验。",
    colorTokens: {
      background: "#151A2D",
      surface: "#202741",
      surfaceAlt: "#2A3352",
      text: "#F7F8FF",
      mutedText: "#AEB7D4",
      primary: "#7C6CFF",
      accent: "#FFB84D",
      border: "#424D76",
      success: "#51D39B",
      warning: "#FFCD62",
      danger: "#FF6E86",
    },
    typography: {
      headingFont: '"Rajdhani", "Noto Sans SC", sans-serif',
      bodyFont: '"Inter", "Noto Sans SC", sans-serif',
      headingWeight: 700,
      bodyWeight: 500,
      baseFontSize: "1rem",
      bodyLineHeight: 1.65,
    },
    spacing: {
      unit: "0.25rem",
      sectionGap: "2rem",
      cardGap: "1rem",
      contentMaxWidth: "74rem",
    },
    surface: {
      cardRadius: "1rem",
      controlRadius: "0.75rem",
      cardBorderWidth: "2px",
      cardShadow: "0 14px 36px rgba(34, 25, 92, 0.34)",
    },
    decoration: {
      pattern: "quest-grid",
      backgroundImage:
        "linear-gradient(135deg, rgba(124,108,255,.16), transparent 35%, rgba(255,184,77,.08))",
      intensity: "bold",
      shapeLanguage: "任务徽章、进度轨道、关卡节点和清晰状态边框",
    },
    motion: {
      durationFast: "130ms",
      durationNormal: "300ms",
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      intensity: "dynamic",
      reducedMotionDuration: "0ms",
    },
    layoutDensity: "comfortable",
    assetGuidance: {
      visualStyle: "高品质游戏任务插画、清晰道具图标和成就徽章",
      composition: "围绕任务目标组织主体，进度与奖励位于明确次级区域",
      background: "深色渐变、低对比关卡地图或抽象任务网格",
      avoid: ["真实赌博元素", "过度闪烁", "与学习目标无关的奖励堆叠"],
    },
    bestFor: ["任务型学习", "闯关练习", "技能挑战", "成就反馈"],
    avoidFor: ["严肃法规说明", "安静自然观察", "纯阅读参考资料"],
    keywords: ["游戏", "任务", "闯关", "挑战", "成就", "进度", "冒险"],
  },
] as const;

/** 启动时校验全部风格，阻止无效 Token 进入 CSS 转换和 Gallery。 */
export const styleTemplates = StyleTemplateSchema.array()
  .length(8)
  .parse(definitions);
