import { FunctionalTemplateSchema } from "./schema";

const definitions = [
  {
    id: "course-cover",
    name: "课程封面",
    pageType: "cover",
    goal: "建立课程主题、学习期待和明确的开始入口。",
    slots: [
      {
        name: "title",
        goal: "呈现课程名称和一句话价值主张。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "用简短引导说明学习者将获得什么。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "interaction",
        goal: "提供开始课程的单一主操作。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "assetSlots",
        goal: "承载代表课程主题的主视觉素材。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
    ],
    constraints: [
      "只介绍课程价值，不提前堆叠知识正文。",
      "主操作只能指向开始学习或继续课程。",
    ],
    bestFor: ["课程第一页", "章节开场", "需要快速建立主题期待的页面"],
    avoidFor: ["知识细节讲解", "形成性测验", "多步骤任务执行"],
    keywords: ["封面", "开场", "课程介绍", "开始", "主题"],
  },
  {
    id: "story-intro",
    name: "故事导入",
    pageType: "story_intro",
    goal: "通过角色、冲突或真实情境激活学习动机并引出问题。",
    slots: [
      {
        name: "title",
        goal: "给出故事场景或核心悬念。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "交代角色、背景和需要解决的问题。",
        required: true,
        minItems: 1,
        maxItems: 3,
      },
      {
        name: "blocks",
        goal: "按顺序呈现关键情节或情境线索。",
        required: true,
        minItems: 1,
        maxItems: 3,
      },
      {
        name: "interaction",
        goal: "邀请学习者预测、选择或接受任务。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "assetSlots",
        goal: "提供角色或场景素材位置。",
        required: false,
        minItems: 0,
        maxItems: 2,
      },
    ],
    constraints: [
      "故事必须服务于学习目标，不能成为无关剧情。",
      "结尾要自然引出下一页的知识或任务。",
    ],
    bestFor: ["新概念导入", "真实问题情境", "角色驱动的儿童课程"],
    avoidFor: ["纯事实速查", "课程最终总结", "需要直接测验的页面"],
    keywords: ["故事", "情境", "角色", "冒险", "案例", "导入"],
  },
  {
    id: "knowledge-card-grid",
    name: "知识卡",
    pageType: "knowledge_card",
    goal: "把同一主题下的多个知识点拆成可独立理解和浏览的卡片。",
    slots: [
      {
        name: "title",
        goal: "概括本组知识卡共同回答的问题。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "给出浏览顺序或观察提示。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "blocks",
        goal: "每个区块承载一个独立但同层级的知识点。",
        required: true,
        minItems: 2,
        maxItems: 6,
      },
      {
        name: "interaction",
        goal: "支持展开、翻转或逐项浏览知识卡。",
        required: false,
        minItems: 0,
        maxItems: 6,
      },
      {
        name: "assetSlots",
        goal: "为每个知识点提供可选的解释性素材。",
        required: false,
        minItems: 0,
        maxItems: 6,
      },
    ],
    constraints: [
      "所有卡片必须处于相同知识层级。",
      "单张卡片只表达一个核心知识点。",
    ],
    bestFor: ["概念集合", "分类知识", "术语与定义", "特征速览"],
    avoidFor: ["强顺序流程", "二元对比", "只包含一个长篇知识点"],
    keywords: ["知识卡", "概念", "分类", "特征", "要点", "术语"],
  },
  {
    id: "comparison-board",
    name: "对比分析",
    pageType: "comparison",
    goal: "围绕统一维度比较两个或多个对象，帮助学习者识别异同。",
    slots: [
      {
        name: "title",
        goal: "明确比较对象和比较问题。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "说明比较维度和阅读方式。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "blocks",
        goal: "按同一组维度呈现各比较对象。",
        required: true,
        minItems: 2,
        maxItems: 4,
      },
      {
        name: "interaction",
        goal: "支持切换维度或判断异同。",
        required: false,
        minItems: 0,
        maxItems: 4,
      },
      {
        name: "assetSlots",
        goal: "为比较对象提供一一对应的素材。",
        required: false,
        minItems: 0,
        maxItems: 4,
      },
    ],
    constraints: [
      "所有对象必须使用同一组比较维度。",
      "结论要解释关键差异，而不是只罗列属性。",
    ],
    bestFor: ["概念辨析", "方案比较", "相似对象区分", "优缺点分析"],
    avoidFor: ["单一对象讲解", "时间顺序过程", "没有共同维度的对象集合"],
    keywords: ["对比", "比较", "区别", "异同", "优缺点", "辨析"],
  },
  {
    id: "learning-timeline",
    name: "学习时间线",
    pageType: "timeline",
    goal: "按时间或阶段顺序呈现事件、演化过程和因果变化。",
    slots: [
      {
        name: "title",
        goal: "说明时间线覆盖的主题和范围。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "提供观察变化或因果关系的提示。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "blocks",
        goal: "每个区块表示一个有序时间点或阶段。",
        required: true,
        minItems: 3,
        maxItems: 8,
      },
      {
        name: "interaction",
        goal: "支持逐步推进或选择时间节点。",
        required: false,
        minItems: 0,
        maxItems: 8,
      },
      {
        name: "assetSlots",
        goal: "为关键节点补充证据或示意素材。",
        required: false,
        minItems: 0,
        maxItems: 8,
      },
    ],
    constraints: [
      "节点顺序必须明确且不可互换。",
      "每个节点要同时说明事件和它带来的变化。",
    ],
    bestFor: ["历史事件", "生命周期", "项目阶段", "技术演进"],
    avoidFor: ["没有顺序关系的知识集合", "二元对比", "单步操作"],
    keywords: ["时间线", "历史", "演变", "阶段", "过程", "先后"],
  },
  {
    id: "interactive-quiz",
    name: "互动选择题",
    pageType: "quiz",
    goal: "通过题目、作答和即时反馈检查学习者对目标知识的理解。",
    slots: [
      {
        name: "title",
        goal: "说明测验主题或挑战目标。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "提供作答规则和完成提示。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
      {
        name: "blocks",
        goal: "每个区块承载一道题目及其选项。",
        required: true,
        minItems: 1,
        maxItems: 8,
      },
      {
        name: "interaction",
        goal: "记录选择并返回正确性、解释和下一步操作。",
        required: true,
        minItems: 1,
        maxItems: 8,
      },
      {
        name: "assetSlots",
        goal: "支持以图片作为题干或选项的补充信息。",
        required: false,
        minItems: 0,
        maxItems: 8,
      },
    ],
    constraints: [
      "每道题必须能映射到明确的学习目标。",
      "反馈要解释原因，不能只显示正确或错误。",
    ],
    bestFor: ["形成性测验", "概念辨析", "知识回忆", "即时自测"],
    avoidFor: ["首次讲解复杂概念", "课程封面", "没有可判断答案的开放讨论"],
    keywords: ["选择题", "问答", "测验", "练习", "判断", "反馈", "挑战"],
  },
  {
    id: "achievement-task",
    name: "任务成就卡",
    pageType: "achievement",
    goal: "把学习目标转化为可执行任务，并在完成后展示成果或成就。",
    slots: [
      {
        name: "title",
        goal: "说明任务名称和期望成果。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "交代任务情境、完成条件和注意事项。",
        required: true,
        minItems: 1,
        maxItems: 2,
      },
      {
        name: "blocks",
        goal: "拆解任务步骤、检查项或成果要求。",
        required: true,
        minItems: 1,
        maxItems: 5,
      },
      {
        name: "interaction",
        goal: "支持提交、勾选完成或确认成就。",
        required: true,
        minItems: 1,
        maxItems: 3,
      },
      {
        name: "assetSlots",
        goal: "提供任务参考或成果展示素材位置。",
        required: false,
        minItems: 0,
        maxItems: 3,
      },
    ],
    constraints: [
      "任务必须有可观察的完成条件。",
      "成就反馈要对应实际完成结果，不能只提供装饰性奖励。",
    ],
    bestFor: ["项目实践", "课后挑战", "操作任务", "学习成果确认"],
    avoidFor: ["纯知识阅读", "没有完成标准的开放问题", "课程首次导入"],
    keywords: ["任务", "挑战", "实践", "完成", "成就", "项目"],
  },
  {
    id: "recap-summary",
    name: "总结复习",
    pageType: "summary",
    goal: "提炼本节关键知识，连接学习目标并提示后续行动。",
    slots: [
      {
        name: "title",
        goal: "说明本次总结覆盖的学习范围。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "narration",
        goal: "用一句话回扣学习目标和总体结论。",
        required: true,
        minItems: 1,
        maxItems: 1,
      },
      {
        name: "blocks",
        goal: "列出需要记住的核心要点。",
        required: true,
        minItems: 2,
        maxItems: 6,
      },
      {
        name: "interaction",
        goal: "支持自我检查、重看重点或进入下一节。",
        required: false,
        minItems: 0,
        maxItems: 3,
      },
      {
        name: "assetSlots",
        goal: "提供一张可选的知识结构或记忆提示素材。",
        required: false,
        minItems: 0,
        maxItems: 1,
      },
    ],
    constraints: [
      "总结必须回扣已出现的内容，不能引入新的核心知识。",
      "要点按学习目标组织，而不是机械复制页面标题。",
    ],
    bestFor: ["章节结尾", "课程复盘", "考试前回顾", "下一步学习提示"],
    avoidFor: ["首次介绍新概念", "详细过程讲解", "需要长篇叙事的页面"],
    keywords: ["总结", "复习", "回顾", "要点", "收尾", "知识地图"],
  },
] as const;

/** 启动时校验全部模板，防止无效定义进入 Registry 和前端。 */
export const functionalTemplates = FunctionalTemplateSchema.array()
  .length(8)
  .parse(definitions);
